version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...

  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - /home/brilworks-41/Practise/employee_details/employee-details/target/employee-details.jar
  discard-paths: yes