version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package

  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - /home/brilworks-41/Practise/employee_details/employee-details/module/target/employee-details.jar  # Update the path accordingly
  discard-paths: yes
